# Generated by Django 4.1.4 on 2023-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
