# Generated by Django 4.1.4 on 2023-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_farmeruser_is_active_alter_farmeruser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
