# Generated by Django 4.1.4 on 2023-08-07 09:06

from django.db import migrations, models
import farm_app.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_farmeruser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
    ]
