# Generated by Django 4.1.4 on 2023-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_farmeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmeruser',
            options={'ordering': ['-date_of_birth', 'username']},
        ),
    ]
