# Generated by Django 4.1.4 on 2024-02-14 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_farmeruser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
    ]
