# Generated by Django 4.1.4 on 2022-12-20 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableAndFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Orange', 'Orange'), ('Other', 'Other'), ('Watermelon', 'Watermelon'), ('Melon', 'Melon'), ('Peach', 'Peach'), ('Lemon', 'Lemon'), ('Blackberry', 'Blackberry'), ('Cherry', 'Cherry'), ('Plum', 'Plum'), ('Pear', 'Pear'), ('Strawberry', 'Strawberry'), ('Grape', 'Grape'), ('Carrot', 'Carrot'), ('Apple', 'Apple'), ('Pumpkin', 'Pumpkin'), ('Corn', 'Corn'), ('Pepper', 'Pepper'), ('Eggplant', 'Eggplant'), ('Broccoli', 'Broccoli'), ('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Cauliflower', 'Cauliflower'), ('Cabbage', 'Cabbage'), ('Potato', 'Potato')], default='Other', max_length=11)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
