# Generated by Django 4.1.4 on 2023-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalproduct',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dairyproduct',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nut',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vegetableandfruit',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
