# Generated by Django 4.1.4 on 2023-07-31 18:05

from django.db import migrations, models
import django.utils.timezone
import farm_app.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_animalproduct_type_alter_dairyproduct_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalproduct',
            old_name='publication_date',
            new_name='date_of_publication',
        ),
        migrations.AddField(
            model_name='animalproduct',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos', validators=[farm_app.catalog.validators.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalproduct',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='dairyproduct',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos', validators=[farm_app.catalog.validators.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nut',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos', validators=[farm_app.catalog.validators.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetableandfruit',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos', validators=[farm_app.catalog.validators.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetableandfruit',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
