# Generated by Django 4.1.4 on 2023-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_animalproduct_photo_alter_dairyproduct_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalproduct',
            name='package',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dairyproduct',
            name='package',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetableandfruit',
            name='package',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalproduct',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
