# Generated by Django 4.1.4 on 2023-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_animalproduct_package_dairyproduct_package_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dairyproduct',
            unique_together=set(),
        ),
    ]
