# Generated by Django 4.1.4 on 2023-08-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_dairyproduct_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetableandfruit',
            name='package',
        ),
    ]
