# Generated by Django 4.1.4 on 2023-08-17 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_animalproduct_date_of_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproduct',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'The name should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='animalproduct',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'The name should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='nut',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'The name should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='vegetableandfruit',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'The name should contain only letters.')]),
        ),
    ]
