# Generated by Django 4.1.4 on 2023-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_vegetableandfruit_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalproduct',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='dairyproduct',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='nut',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='vegetableandfruit',
            options={'ordering': ['-price']},
        ),
    ]
