# Generated by Django 4.1.4 on 2024-02-14 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_animalproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproduct',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='animalproduct',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='nut',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='vegetableandfruit',
            name='production',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+)?$', 'The value should contain only letters.')]),
        ),
    ]
