# Generated by Django 4.0.2 on 2024-08-24 13:10

from django.db import migrations, models
import farm_app.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_animalproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='dairyproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='nut',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='nut',
            name='type',
            field=models.CharField(choices=[('Roasted', 'ROASTED'), ('Raw', 'RAW'), ('Dried', 'DRIED_FRUIT'), ('Other', 'OTHER')], default='Other', max_length=7),
        ),
        migrations.AlterField(
            model_name='vegetableandfruit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
    ]
