# Generated by Django 4.1.4 on 2023-11-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_dairy_alter_orderitem_fruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='city',
        ),
    ]
