# Generated by Django 4.1.4 on 2023-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(max_length=4),
        ),
    ]
