# Generated by Django 4.1.4 on 2023-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_phone_alter_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
