# Generated by Django 4.1.4 on 2024-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_address_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
