# Generated by Django 4.1.4 on 2024-01-22 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_phone_alter_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'The value should contain only digits.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'The value should contain only digits.')]),
        ),
    ]
